import type {
  User,
  Instrument,
  VerificationApplication,
  DigitalCertificate,
  InspectionRecord,
  AuditLog,
  NoticeBoardItem,
  GATCInfo,
} from '../types';

export const DEMO_USERS: Record<string, User> = {
  trader: {
    id: 'USR-TRADER-001',
    name: 'Rajesh Sharma',
    email: 'trader@demo.com',
    role: 'trader',
    designation: 'Managing Director',
    organization: 'Apex Logistics & Grain Mills Pvt Ltd',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  officer: {
    id: 'USR-OFFICER-102',
    name: 'Inspector Vikramaditya Roy',
    email: 'officer@demo.com',
    role: 'officer',
    designation: 'Senior Legal Metrology Officer (LMO)',
    organization: 'Department of Legal Metrology, Delhi Circle-IV',
    phone: '+91 98112 34567',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  gatc: {
    id: 'USR-GATC-204',
    name: 'Dr. Sunita Deshmukh',
    email: 'gatc@demo.com',
    role: 'gatc',
    designation: 'Technical Manager',
    organization: 'National Metrology Test Lab (GATC-089)',
    phone: '+91 94220 11223',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  admin: {
    id: 'USR-ADMIN-001',
    name: 'Amitabh Sen, IAS',
    email: 'admin@demo.com',
    role: 'admin',
    designation: 'Controller of Legal Metrology',
    organization: 'Ministry of Consumer Affairs, Govt. of India',
    phone: '+91 91100 00001',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_INSTRUMENTS: Instrument[] = [
  {
    id: 'INST-WB-8821',
    title: 'Heavy Duty Weighing Scale (Electronic Weighbridge 60T)',
    category: 'Weighbridge',
    manufacturer: 'Avery India Ltd',
    modelNumber: 'AV-WB60T-PRO',
    serialNumber: 'SN-WB-2024-998',
    capacity: '60,000 kg (60 Tonnes)',
    accuracyClass: 'Class III',
    locationAddress: 'Plot 45, Okhla Industrial Area Phase-3',
    city: 'New Delhi',
    state: 'Delhi',
    purchaseDate: '2024-03-15',
    ownerId: 'USR-TRADER-001',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    ownerPhone: '+91 98765 43210',
    status: 'INSPECTION_SCHEDULED',
    currentCertNo: 'LM-DEL-2026-004821',
    certExpiryDate: '2026-10-20',
    photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80',
    invoiceUrl: 'invoice_wb60t.pdf',
    createdAt: '2024-03-20',
  },
  {
    id: 'INST-FD-4012',
    title: 'Fuel Dispensing Unit (Multi-Nozzle Petrol & Diesel)',
    category: 'Fuel Dispenser',
    manufacturer: 'Midco Limited',
    modelNumber: 'MD-FD-DUO-50',
    serialNumber: 'SN-FD-2023-412',
    capacity: '50 Litres/min',
    accuracyClass: 'Class 0.5',
    locationAddress: 'HP Fuel Station, NH-48 Express Highway',
    city: 'Gurugram',
    state: 'Haryana',
    purchaseDate: '2023-08-10',
    ownerId: 'USR-TRADER-001',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    ownerPhone: '+91 98765 43210',
    status: 'EXPIRING_SOON',
    currentCertNo: 'LM-HAR-2025-001920',
    certExpiryDate: '2026-09-17',
    photoUrl: 'https://images.unsplash.com/photo-1527018606416-a65453770388?w=600&auto=format&fit=crop&q=80',
    invoiceUrl: 'invoice_fd4012.pdf',
    createdAt: '2023-08-15',
  },
  {
    id: 'INST-WS-1055',
    title: 'Digital Platform Weighing Scale',
    category: 'Weighing Scale',
    manufacturer: 'Essae-Teraoka Ltd',
    modelNumber: 'DS-215-HD',
    serialNumber: 'SN-WS-2025-331',
    capacity: '300 kg (Div: 50g)',
    accuracyClass: 'Class III',
    locationAddress: 'Warehouse B-12, Sector 63',
    city: 'Noida',
    state: 'Uttar Pradesh',
    purchaseDate: '2025-01-10',
    ownerId: 'USR-TRADER-001',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    ownerPhone: '+91 98765 43210',
    status: 'VERIFICATION_PENDING',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2026-09-01',
  },
  {
    id: 'INST-WM-3310',
    title: 'Electromagnetic Ultrasonic Industrial Water Meter',
    category: 'Water Meter',
    manufacturer: 'Krohne Marshall',
    modelNumber: 'WATER-FLUX-3070',
    serialNumber: 'SN-WM-2022-881',
    capacity: '100 m³/hr',
    accuracyClass: 'Class B',
    locationAddress: 'Plant No. 3, Industrial Corridor',
    city: 'Faridabad',
    state: 'Haryana',
    purchaseDate: '2022-05-20',
    ownerId: 'USR-TRADER-001',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    ownerPhone: '+91 98765 43210',
    status: 'EXPIRED',
    currentCertNo: 'LM-HAR-2024-000881',
    certExpiryDate: '2026-08-15',
    photoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
    createdAt: '2022-05-25',
  },
];

export const INITIAL_APPLICATIONS: VerificationApplication[] = [
  {
    id: 'APP-2026-1403',
    applicationNo: 'APP-2026-1403',
    instrumentId: 'INST-WB-8821',
    instrumentTitle: 'Heavy Duty Weighing Scale (Electronic Weighbridge 60T)',
    category: 'Weighbridge',
    serialNumber: 'SN-WB-2024-998',
    ownerId: 'USR-TRADER-001',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    applicationType: 'VERIFICATION',
    submissionDate: '2026-08-18',
    scheduledInspectionDate: '2026-09-18',
    assignedOfficerId: 'USR-OFFICER-102',
    assignedOfficerName: 'Inspector Vikramaditya Roy',
    feeAmount: 3500,
    paymentStatus: 'PAID',
    paymentTransactionId: 'TXN-UPI-992014881',
    status: 'INSPECTION_SCHEDULED',
    documents: {
      purchaseInvoice: 'invoice_wb60t.pdf',
      instrumentPhoto: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80',
      calibrationReport: 'calib_wb60t.pdf',
    },
    timeline: [
      { title: 'Application Submitted', description: 'Application filed online by trader', timestamp: '18 Aug 2026 10:30 AM', completed: true },
      { title: 'Documents Verified', description: 'Purchase invoice & calibration report verified', timestamp: '19 Aug 2026 02:15 PM', completed: true },
      { title: 'Fee Paid', description: 'Statutory verification fee ₹3500 paid online', timestamp: '19 Aug 2026 02:20 PM', completed: true },
      { title: 'Officer Assigned', description: 'Assigned to Inspector Vikramaditya Roy', timestamp: '20 Aug 2026 11:00 AM', completed: true },
      { title: 'Inspection Scheduled', description: 'Scheduled for Field Verification on 18 Sep 2026', timestamp: '21 Aug 2026 09:30 AM', completed: true, current: true },
      { title: 'Inspection Completed', description: 'LMO on-site tolerance testing & sealing', completed: false },
      { title: 'Certificate Issued', description: 'Issuance of digital certificate with QR Code', completed: false },
    ],
  },
  {
    id: 'APP-2026-9012',
    applicationNo: 'APP-2026-9012',
    instrumentId: 'INST-WS-1055',
    instrumentTitle: 'Digital Platform Weighing Scale',
    category: 'Weighing Scale',
    serialNumber: 'SN-WS-2025-331',
    ownerId: 'USR-TRADER-001',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    applicationType: 'VERIFICATION',
    submissionDate: '2026-09-02',
    scheduledInspectionDate: '2026-09-15',
    assignedOfficerId: 'USR-OFFICER-102',
    assignedOfficerName: 'Inspector Vikramaditya Roy',
    feeAmount: 1250,
    paymentStatus: 'PAID',
    paymentTransactionId: 'TXN-UPI-77109281',
    status: 'DOCUMENTS_VERIFIED',
    documents: {
      purchaseInvoice: 'invoice_ws1055.pdf',
      instrumentPhoto: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    },
    timeline: [
      { title: 'Application Submitted', description: 'Application filed online by trader', timestamp: '02 Sep 2026 11:00 AM', completed: true },
      { title: 'Documents Verified', description: 'Document verification completed by inspector', timestamp: '03 Sep 2026 04:00 PM', completed: true, current: true },
      { title: 'Fee Paid', description: 'Statutory verification fee ₹1250 paid online', timestamp: '03 Sep 2026 04:05 PM', completed: true },
      { title: 'Officer Assigned', description: 'Assigned to Inspector Vikramaditya Roy', completed: false },
      { title: 'Inspection Scheduled', description: 'Pending scheduling', completed: false },
      { title: 'Inspection Completed', description: 'Awaiting field test', completed: false },
      { title: 'Certificate Issued', description: 'Awaiting approval', completed: false },
    ],
  },
  {
    id: 'APP-2026-8801',
    applicationNo: 'APP-2026-8801',
    instrumentId: 'INST-FD-4012',
    instrumentTitle: 'Fuel Dispensing Unit (Multi-Nozzle Petrol & Diesel)',
    category: 'Fuel Dispenser',
    serialNumber: 'SN-FD-2023-412',
    ownerId: 'USR-TRADER-001',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    applicationType: 'RE_VERIFICATION',
    submissionDate: '2025-09-10',
    scheduledInspectionDate: '2025-09-17',
    assignedOfficerId: 'USR-OFFICER-102',
    assignedOfficerName: 'Inspector Vikramaditya Roy',
    feeAmount: 2500,
    paymentStatus: 'PAID',
    paymentTransactionId: 'TXN-CARD-9910401',
    status: 'CERTIFICATE_GENERATED',
    documents: {
      purchaseInvoice: 'invoice_fd4012.pdf',
    },
    timeline: [
      { title: 'Application Submitted', description: 'Re-verification filed online', timestamp: '10 Sep 2025 09:00 AM', completed: true },
      { title: 'Documents Verified', description: 'Approved', timestamp: '11 Sep 2025 11:30 AM', completed: true },
      { title: 'Fee Paid', description: 'Fee ₹2500 paid', timestamp: '11 Sep 2025 11:35 AM', completed: true },
      { title: 'Officer Assigned', description: 'Inspector Vikramaditya Roy', timestamp: '12 Sep 2025 04:00 PM', completed: true },
      { title: 'Inspection Scheduled', description: 'Scheduled for 17 Sep 2025', timestamp: '13 Sep 2025 10:00 AM', completed: true },
      { title: 'Inspection Completed', description: 'Tolerance test passed', timestamp: '17 Sep 2025 02:30 PM', completed: true },
      { title: 'Certificate Issued', description: 'LM-HAR-2025-001920 issued', timestamp: '17 Sep 2025 03:00 PM', completed: true },
    ],
  },
];

export const INITIAL_CERTIFICATES: DigitalCertificate[] = [
  {
    certNo: 'LM-DEL-2026-004821',
    applicationId: 'APP-2026-1403',
    instrumentId: 'INST-WB-8821',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    ownerPhone: '+91 98765 43210',
    ownerAddress: 'Plot 45, Okhla Industrial Area Phase-3, New Delhi - 110020',
    instrumentCategory: 'Weighbridge',
    manufacturer: 'Avery India Ltd',
    modelNumber: 'AV-WB60T-PRO',
    serialNumber: 'SN-WB-2024-998',
    capacity: '60,000 kg (60 Tonnes)',
    verificationDate: '2025-10-20',
    validUntilDate: '2026-10-20',
    issuingOfficerName: 'Inspector Vikramaditya Roy',
    issuingOfficerDesignation: 'Senior Legal Metrology Officer (LMO)',
    verificationAuthority: 'Department of Legal Metrology, Govt. of NCT of Delhi',
    securityHash: '8f9b4c1a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a',
    qrCodeUrl: 'https://e-metro.gov.in/verify?cert=LM-DEL-2026-004821',
    status: 'VALID',
  },
  {
    certNo: 'LM-HAR-2025-001920',
    applicationId: 'APP-2026-8801',
    instrumentId: 'INST-FD-4012',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    ownerPhone: '+91 98765 43210',
    ownerAddress: 'HP Fuel Station, NH-48 Express Highway, Gurugram - 122001',
    instrumentCategory: 'Fuel Dispenser',
    manufacturer: 'Midco Limited',
    modelNumber: 'MD-FD-DUO-50',
    serialNumber: 'SN-FD-2023-412',
    capacity: '50 Litres/min',
    verificationDate: '2025-09-17',
    validUntilDate: '2026-09-17',
    issuingOfficerName: 'Inspector Vikramaditya Roy',
    issuingOfficerDesignation: 'Senior Legal Metrology Officer (LMO)',
    verificationAuthority: 'Department of Legal Metrology, Haryana State',
    securityHash: '3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b',
    qrCodeUrl: 'https://e-metro.gov.in/verify?cert=LM-HAR-2025-001920',
    status: 'VALID',
  },
  {
    certNo: 'LM-HAR-2024-000881',
    applicationId: 'APP-2024-1102',
    instrumentId: 'INST-WM-3310',
    ownerName: 'Apex Logistics & Grain Mills Pvt Ltd',
    ownerEmail: 'trader@demo.com',
    ownerPhone: '+91 98765 43210',
    ownerAddress: 'Plant No. 3, Industrial Corridor, Faridabad',
    instrumentCategory: 'Water Meter',
    manufacturer: 'Krohne Marshall',
    modelNumber: 'WATER-FLUX-3070',
    serialNumber: 'SN-WM-2022-881',
    capacity: '100 m³/hr',
    verificationDate: '2024-08-15',
    validUntilDate: '2026-08-15',
    issuingOfficerName: 'Dr. Sunita Deshmukh',
    issuingOfficerDesignation: 'Technical Manager (GATC-089)',
    verificationAuthority: 'National Metrology Test Lab (GATC-089)',
    securityHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    qrCodeUrl: 'https://e-metro.gov.in/verify?cert=LM-HAR-2024-000881',
    status: 'EXPIRED',
  },
];

export const INITIAL_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'INSP-2025-901',
    applicationId: 'APP-2026-1403',
    instrumentId: 'INST-WB-8821',
    officerId: 'USR-OFFICER-102',
    officerName: 'Inspector Vikramaditya Roy',
    inspectionDate: '2025-10-20',
    locationGeo: '28.5355° N, 77.2610° E (Accuracy: ±2m)',
    locationAddress: 'Plot 45, Okhla Industrial Area Phase-3, New Delhi',
    checklist: [
      { id: 'c1', label: 'Instrument identification & brand tag verified', checked: true },
      { id: 'c2', label: 'Manufacturer model & approval certificate verified', checked: true },
      { id: 'c3', label: 'Serial number on body matches application document', checked: true },
      { id: 'c4', label: 'Physical condition, leveling bubble & zero setting satisfactory', checked: true },
      { id: 'c5', label: 'Standard test weights verified against NPL standard', checked: true },
      { id: 'c6', label: 'Maximum permissible error (MPE) within prescribed limits', checked: true },
      { id: 'c7', label: 'Anti-tamper lead seal requirement satisfied', checked: true },
    ],
    testReadings: [
      { parameter: 'Minimum Load Test (500 kg)', standardValue: 500, observedValue: 500.1, unit: 'kg', toleranceMargin: 0.05, errorPercentage: 0.02, result: 'PASS' },
      { parameter: 'Half Load Test (30,000 kg)', standardValue: 30000, observedValue: 30005, unit: 'kg', toleranceMargin: 0.05, errorPercentage: 0.016, result: 'PASS' },
      { parameter: 'Full Capacity Test (60,000 kg)', standardValue: 60000, observedValue: 60012, unit: 'kg', toleranceMargin: 0.05, errorPercentage: 0.02, result: 'PASS' },
      { parameter: 'Eccentricity (Corner Load Test)', standardValue: 15000, observedValue: 15002, unit: 'kg', toleranceMargin: 0.05, errorPercentage: 0.013, result: 'PASS' },
      { parameter: 'Repeatability Test', standardValue: 30000, observedValue: 30003, unit: 'kg', toleranceMargin: 0.05, errorPercentage: 0.01, result: 'PASS' },
    ],
    observations: 'Instrument load cells calibrated cleanly. Anti-tamper lead seal (LM-SEAL-88410) applied successfully.',
    photos: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80',
    ],
    finalResult: 'PASS',
    submittedAt: '2025-10-20 02:45 PM',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'LOG-10091',
    timestamp: '2026-09-08 04:20:11',
    userId: 'USR-TRADER-001',
    userName: 'Rajesh Sharma',
    userRole: 'trader',
    action: 'APPLICATION_SUBMITTED',
    targetId: 'APP-2026-1403',
    details: 'Submitted verification request for Heavy Duty Weighing Scale (SN-WB-2024-998) with fee ₹3500',
    ipAddress: '49.206.121.84',
  },
  {
    id: 'LOG-10090',
    timestamp: '2026-09-05 09:30:45',
    userId: 'USR-OFFICER-102',
    userName: 'Inspector Vikramaditya Roy',
    userRole: 'officer',
    action: 'INSPECTION_SCHEDULED',
    targetId: 'APP-2026-1403',
    details: 'Scheduled field inspection for 18 Sep 2026 at Okhla Industrial Area',
    ipAddress: '14.139.60.10',
  },
  {
    id: 'LOG-10089',
    timestamp: '2026-09-02 10:30:00',
    userId: 'USR-TRADER-001',
    userName: 'Rajesh Sharma',
    userRole: 'trader',
    action: 'INSTRUMENT_REGISTERED',
    targetId: 'INST-WS-1055',
    details: 'Registered new Weighing Scale DS-215-HD (Serial: SN-WS-2025-331)',
    ipAddress: '49.206.121.84',
  },
  {
    id: 'LOG-10088',
    timestamp: '2025-10-20 03:00:12',
    userId: 'USR-OFFICER-102',
    userName: 'Inspector Vikramaditya Roy',
    userRole: 'officer',
    action: 'CERTIFICATE_ISSUED',
    targetId: 'LM-DEL-2026-004821',
    details: 'Issued digital verification certificate with QR Code for Weighbridge INST-WB-8821',
    ipAddress: '14.139.60.10',
  },
];

export const OFFICIAL_NOTICES: NoticeBoardItem[] = [
  {
    id: 'NOT-2026-041',
    title: 'Revised Fee Structure for Commercial Weighing & Measuring Instruments (Schedule-IX Rules)',
    date: '01 Sep 2026',
    category: 'Fee Structure',
    isNew: true,
  },
  {
    id: 'NOT-2026-039',
    title: 'Mandatory Re-Verification & Stamping Schedule for Fuel Dispensers & Flow Meters 2026-27',
    date: '24 Aug 2026',
    category: 'Circular',
    isNew: true,
  },
  {
    id: 'NOT-2026-035',
    title: 'Guidelines for Traders on Digital Certificate Verification & QR Code Display Requirements',
    date: '10 Aug 2026',
    category: 'Guidelines',
  },
  {
    id: 'NOT-2026-028',
    title: 'List of Government Approved Test Centres (GATC) Accredited under Section 24A for FY 2026',
    date: '15 Jul 2026',
    category: 'GATC List',
  },
];

export const GATC_DIRECTORY: GATCInfo[] = [
  {
    id: 'GATC-089',
    code: 'NMTL-DEL-089',
    name: 'National Metrology Test Laboratory (GATC-089)',
    location: 'Okhla Industrial Area Phase-2',
    state: 'Delhi NCT',
    accreditationNo: 'NABL-LM-2026-8819',
    contactPerson: 'Dr. Sunita Deshmukh',
    phone: '+91 94220 11223',
    email: 'gatc@demo.com',
    categories: ['Water Meter', 'Electricity Meter', 'Measuring Equipment'],
    status: 'ACTIVE',
  },
  {
    id: 'GATC-042',
    code: 'PMTL-HAR-042',
    name: 'Precision Metrology Test House (GATC-042)',
    location: 'Udyog Vihar Phase-4',
    state: 'Haryana (Gurugram)',
    accreditationNo: 'NABL-LM-2025-4102',
    contactPerson: 'Er. Rajesh Kulkarni',
    phone: '+91 98112 00192',
    email: 'contact@pmtl.gov.in',
    categories: ['Fuel Dispenser', 'Measuring Equipment'],
    status: 'ACTIVE',
  },
  {
    id: 'GATC-105',
    code: 'BMTL-KAR-105',
    name: 'Bengaluru Metrology Testing Centre (GATC-105)',
    location: 'Peenya Industrial Estate',
    state: 'Karnataka (Bengaluru)',
    accreditationNo: 'NABL-LM-2026-9920',
    contactPerson: 'Dr. Ramesh Gowda',
    phone: '+91 94480 33112',
    email: 'info@bmtl.org.in',
    categories: ['Weighbridge', 'Weighing Scale', 'Water Meter'],
    status: 'ACTIVE',
  },
];
